CREATE TABLE Notifications (
    NotificationID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL,
    Title NVARCHAR(200) NOT NULL,
    Message NVARCHAR(MAX) NOT NULL,
    Type NVARCHAR(50) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT(GETDATE()),
    IsRead BIT NOT NULL DEFAULT(0),
    RelatedEntityID INT NULL,
    CONSTRAINT FK_Notifications_Users FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Chats (
    ChatID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    IsGroup BIT NOT NULL DEFAULT(1),
    CreatedAt DATETIME NOT NULL DEFAULT(GETDATE())
);

CREATE TABLE ChatParticipants (
    ChatParticipantID INT IDENTITY(1,1) PRIMARY KEY,
    ChatID INT NOT NULL,
    UserID INT NOT NULL,
    CONSTRAINT FK_ChatParticipants_Chats FOREIGN KEY (ChatID) REFERENCES Chats(ChatID),
    CONSTRAINT FK_ChatParticipants_Users FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Messages (
    MessageID INT IDENTITY(1,1) PRIMARY KEY,
    ChatID INT NOT NULL,
    SenderID INT NOT NULL,
    MessageText NVARCHAR(MAX) NOT NULL,
    SentAt DATETIME NOT NULL DEFAULT(GETDATE()),
    IsRead BIT NOT NULL DEFAULT(0),
    CONSTRAINT FK_Messages_Chats FOREIGN KEY (ChatID) REFERENCES Chats(ChatID),
    CONSTRAINT FK_Messages_Users FOREIGN KEY (SenderID) REFERENCES Users(UserID)
);
