//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerOfItProjects.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUsers
    {
        public int ProjectUserID { get; set; }
        public int ProjectID { get; set; }
        public int UserID { get; set; }
        public int ProjectRoleID { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
    
        public virtual ProjectRole ProjectRole { get; set; }
        public virtual Projects Projects { get; set; }
        public virtual Users Users { get; set; }
    }
}
