//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerOfItProjects.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectResources
    {
        public int ResourceID { get; set; }
        public int ProjectID { get; set; }
        public string ResourceName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Description { get; set; }
    
        public virtual Projects Projects { get; set; }
    }
}
